feat: forc-client points empty accounts to beta-4 faucet (#4972)
## Description
closes #4862.

waiting for #4905 to be merged first.

With this PR, we are now pointing empty accounts to beta-4 faucet with
their address already inserted so that people can click on it and get
funded.

```console
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet": 
Error: Your wallet does not have any funds to pay for the transaction.

If you are interacting with a testnet consider using the faucet.
-> beta-4 network faucet: https://faucet-beta-4.fuel.network/?address=fuel1l6su7ldka75ntmz7vx05tfznshxjpa4ftt4p537vl2ck45a5p5tsmwjevm
If you are interacting with a local node, consider providing a chainConfig which funds your account.
```

---------

Co-authored-by: Sophie Dankel <47993817+sdankel@users.noreply.github.com>